// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swvvenarnqewpocscohr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dnZlbmFybnFld3BvY3Njb2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MzQwMDEsImV4cCI6MjA3NTMxMDAwMX0.jK7aF2aor4sYgEOetUW6husTF_Xr9jp5bCL_qqS3smE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});